<?php

/**
 * Created by PhpStorm.
 * User: Mani
 * Date: 20.1.2017
 * Time: 10:43
 */

    namespace Movieclass;

class Movies
{

    function getMovieInfo($tala){ #CSV metaskrá, sem inniheldur yfir 5000 titla, vinnum samt bara med 100 titla
        $File = 'movie_metadata.csv'; #file sem oli gaf mer til ad audvelda vinnuna :)
        $arrayRes  = array(); #skilgreinir array sem tekur a moti upplysingunum
        $handle     = fopen($File, "r");
        if(empty($handle) === false) {
            while(($data = fgetcsv($handle, 1000, ",")) !== FALSE){
                $arrayRes[] = $data;
            }
            fclose($handle);
        }
        $directors = []; #Initializa array-in sem eg ætla ad vinna med
        $movies = [];
        $duration = [];
        $rating = [];
        $actor = [];
        for($i = 0; $i < 150; $i++) #Hér er hægt aðgera count($arrayRes og tekið  allt, en við látum 100 duga
        {
            array_push($directors,$arrayRes[$i][1]); #Hérna fara upplýsingar í sitt viðeigandi array
            $part1 = substr($arrayRes[$i][11],0,-1);
            array_push($movies,$part1);
            array_push($duration,$arrayRes[$i][3]);
            array_push($rating,$arrayRes[$i][25]);
            array_push($actor,$arrayRes[$i][10]);
        }
        $movie = [];
        array_push($movie,$directors[$tala],$movies[$tala],$duration[$tala],$rating[$tala],$actor[$tala]); #Hérna sameina ég svo allar viðeigandi upplýsingar í sama Array
        /* echo("$movie[0], $movie[1], $movie[2], $movie[3]"); */
        return $movie;
    } #Fallið vinnur með CSV skrána og skilar array-inu
    public $name; #breytur
    public $producer;
    public $length;
    public $rating;
    public function __construct($tala) #Constructor tekur inn $tala og notar getmovie functionið til að fá upplysingar
    {
        $movieinfo = $this->getMovieInfo($tala);
        $this->name = $movieinfo[1] ;
        $this->producer = $movieinfo[0];
        $this->length = $movieinfo[2];
        $this->rating = $movieinfo[3];
    }
        public function __toString() #Hérna er ég að segja þessu að birtast svona þegar ég echoa þetta
        {
            return "Movie Name: ". $this->name ."<br>".
                "Producer Name: ". $this->producer . "<br>".
                "Length Movie:".$this->length." mín <br>".
                "Movie Rating: ".$this->rating."<br>";
        }
}

class Actors extends Movies # Hérna bý ég til subclassa sem erfir allt frá Movies klasanum og skilar því sama, nema hann geymir upplýsingarnar um leikarann
{
    public $actor;
    public function __construct($tala) #alveg eins og parent klasinn að þá tekur klasinn tölu og vinnur með þá tölu ($tala)
    {   $movieinfo = $this->getMovieInfo($tala);
        parent::__construct($tala);
        $this->actor = $movieinfo[4];
    }
    public function __toString() # tekur parent tostring aðferðina nema bætir við aukatexta
    {
        return parent::__toString() . "Main Actor: ".$this->actor."<br>"; // TODO: Change the autogenerated stub
    }
}
